name: quill_delta
description: Simple and expressive format for describing rich-text content created for Quill.js editor. This package is unofficial port to Dart from JavaScript.
version: 2.0.0
homepage: https://github.com/pulyaevskiy/quill-delta-dart
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.14.5
  quiver: ^3.0.0-nullsafety.3

dev_dependencies:
  test: ^1.16.0
  test_coverage: ^0.5.0
  pedantic: ^1.9.2
